-- Ideas vault table.
-- UUIDs and timestamps are generated by the Worker so the schema remains
-- portable across local and remote D1 databases.
CREATE TABLE IF NOT EXISTS ideas (
  id TEXT PRIMARY KEY,
  raw TEXT NOT NULL,
  efficiency TEXT NOT NULL,
  friction_killer TEXT NOT NULL,
  unit_economics TEXT NOT NULL,
  created_at TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS ideas_created_at_idx ON ideas (created_at DESC);
